
variables:
  System.Debug: true

trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel
      #ref: refs/tags/0.2

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    caption: Basic
    vcpkgRef: ba2298b26ce17b5248685d30b359185485413674
    #vcpkgOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
    #vcpkgOverlayRef: 28b52673c26e29ccdce93ffa78413f26a0b11c8f
    #vcpkgPackages: ['cmakeshift', 'gsl-lite']
    vcpkgPackages: ['gsl-lite']

    cmakeSourceDir: '$(Build.SourcesDirectory)/ci/basic'
    cmakeConfigArgs: '-DBUILD_TESTING=ON -DCMAKESHIFT_WARNING_LEVEL=high'
    #cmakeTestArgs: '--exclude-regex cuda' # do not run CUDA tests

    postSetupSteps:
    - pwsh: |
        Write-Host 'Custom post-setup step (global)'
        Write-Host "C++ compiler: $env:CIMAKESHIFT_CXX_COMPILER, version: $env:CIMAKESHIFT_CXX_COMPILER_VERSION"
        Write-Host "CUDA compiler: $env:CIMAKESHIFT_CUDA_COMPILER, version: $env:CIMAKESHIFT_CUDA_COMPILER_VERSION"
      displayName: 'Custom post-setup step (global)'

    preBuildSteps:
    - pwsh: |
        Write-Host 'Custom pre-build step (global)'
        Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
      displayName: 'Custom pre-build step (global)'

    postBuildSteps:
    - pwsh: |
        Write-Host 'Custom post-build step (global)'
        Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
      displayName: 'Custom post-build step (global)'

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2, 19_3]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_3]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_8]
      platforms: [x64]
      vcpkgPackages: ['<vcpkgPackages>', 'catch2']
      cudaPackages: ['nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_3]
      cudaCompiler: NVCC
      cudaCompilerVersions: [12_1]
      platforms: [x64]
      vcpkgPackages: ['<vcpkgPackages>', 'catch2']
      cudaPackages: ['nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

      postSetupSteps:
      - pwsh: |
          Write-Host 'Custom post-setup step (target)'
          Write-Host "C++ compiler: $env:CIMAKESHIFT_CXX_COMPILER, version: $env:CIMAKESHIFT_CXX_COMPILER_VERSION"
          Write-Host "CUDA compiler: $env:CIMAKESHIFT_CUDA_COMPILER, version: $env:CIMAKESHIFT_CUDA_COMPILER_VERSION"
        displayName: 'Custom post-setup step (target)'

      preBuildSteps:
      - pwsh: |
          Write-Host 'Custom pre-build step (target)'
          Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
        displayName: 'Custom pre-build step (target)'

      postBuildSteps:
      - pwsh: |
          Write-Host 'Custom post-build step (target)'
          Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
        displayName: 'Custom post-build step (target)'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [7, 12]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer]
      platforms: [x64]
      tag: 'sanitize'
      cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [6, 13]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [17]
      cxxStandardLibrary: libstdc++
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer, ImplicitIntegerArithmeticValueChange]
      platforms: [x64]
      tag: 'sanitize'
      vcpkgTriplet: <platform>-<os>
      cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [8]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_8]
      platforms: [x64]
      vcpkgPackages: ['catch2', 'gsl-lite']
      cudaPackages: ['<cudaPackages>', 'nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [12]
      cudaCompiler: NVCC
      cudaCompilerVersions: [12_3]
      platforms: [x64]
      cudaPackages: ['<cudaPackages>', 'nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [10, 11, 12, 13]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      #cxxCompilerVersions: [10_0_1, 14, 14_0_3]
      cxxCompilerVersions: [10_0_1, 15]
      platforms: [x64]

- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    caption: Vcpkg manifests
    vcpkgRef: f78f4440df86358575dea65e748a39fdad41eb85

    cmakeSourceDir: '$(Build.SourcesDirectory)/ci/vcpkg-manifest'
    cmakeConfigArgs: '-DBUILD_TESTING=ON -DCMAKESHIFT_WARNING_LEVEL=high'

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_3]
      platforms: [x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2022]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [17]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [13]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [13_1_6, 14_0_3, 15_2]
      platforms: [x64]
