
variables:
  System.Debug: true

trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel
      #ref: refs/tags/0.2

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    caption: Basic
    vcpkgRef: 00e44369cb23f911821ee96888cbb4785810ba07
    vcpkgOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
    vcpkgOverlayRef: 28b52673c26e29ccdce93ffa78413f26a0b11c8f
    vcpkgPackages: ['cmakeshift', 'gsl-lite']

    cmakeSourceDir: '$(Build.SourcesDirectory)/ci/basic'
    cmakeConfigArgs: '-DBUILD_TESTING=ON'
    #cmakeTestArgs: '--exclude-regex cuda' # do not run CUDA tests

    postSetupSteps:
    - pwsh: |
        Write-Host 'Custom post-setup step (global)'
        Write-Host "C++ compiler: $env:CIMAKESHIFT_CXX_COMPILER, version: $env:CIMAKESHIFT_CXX_COMPILER_VERSION"
        Write-Host "CUDA compiler: $env:CIMAKESHIFT_CUDA_COMPILER, version: $env:CIMAKESHIFT_CUDA_COMPILER_VERSION"
      displayName: 'Custom post-setup step (global)'

    preBuildSteps:
    - pwsh: |
        Write-Host 'Custom pre-build step (global)'
        Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
      displayName: 'Custom pre-build step (global)'

    postBuildSteps:
    - pwsh: |
        Write-Host 'Custom post-build step (global)'
        Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
      displayName: 'Custom post-build step (global)'

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_1, 19_2]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [9, 10]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2]
      cudaCompiler: NVCC
      cudaCompilerVersions: [10_2]
      platforms: [x64]
      vcpkgPackages: ['<vcpkgPackages>', 'catch2']
      cudaPackages: ['nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

      postSetupSteps:
      - pwsh: |
          Write-Host 'Custom post-setup step (target)'
          Write-Host "C++ compiler: $env:CIMAKESHIFT_CXX_COMPILER, version: $env:CIMAKESHIFT_CXX_COMPILER_VERSION"
          Write-Host "CUDA compiler: $env:CIMAKESHIFT_CUDA_COMPILER, version: $env:CIMAKESHIFT_CUDA_COMPILER_VERSION"
        displayName: 'Custom post-setup step (target)'

      preBuildSteps:
      - pwsh: |
          Write-Host 'Custom pre-build step (target)'
          Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
        displayName: 'Custom pre-build step (target)'

      postBuildSteps:
      - pwsh: |
          Write-Host 'Custom post-build step (target)'
          Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
        displayName: 'Custom post-build step (target)'

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_0]
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [5, 6, 7, 8, 9]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [10]
      platforms: [x64]
      tag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeBuildConfigurations: [Debug]
      cmakeConfigArgs: '<cmakeConfigArgs> -DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [4, 5, 6, 7, 8, 9]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [10]
      platforms: [x64]
      tag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeBuildConfigurations: [Debug]
      cmakeConfigArgs: '<cmakeConfigArgs> -DCMAKESHIFT_PRIVATE_COMPILE_SETTINGS=runtime-checks;debug-stdlib'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [8]
      cudaCompiler: NVCC
      cudaCompilerVersions: [10_2]
      platforms: [x64]
      vcpkgPackages: ['catch2', 'cmakeshift', 'gsl-lite']
      cudaPackages: ['<cudaPackages>', 'nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [9]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_0]
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [5, 6, 7, 8, 9, 10]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [9_1, 10, 10_0_1, 11, 11_0_3]
      platforms: [x64]

- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    caption: Vcpkg manifests
    vcpkgRef: 00e44369cb23f911821ee96888cbb4785810ba07

    cmakeSourceDir: '$(Build.SourcesDirectory)/ci/vcpkg-manifest'
    cmakeConfigArgs: '-DBUILD_TESTING=ON'

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2]
      platforms: [x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [10]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [10]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [10]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [10]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [11_0_3]
      platforms: [x64]
