
variables:
  System.Debug: true

trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel
      #ref: refs/tags/0.2

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    caption: Basic
    vcpkgRef: f79c681fc2b42f9c7c5024459b5a867d56ac6123
    #vcpkgOverlayRepo: 'https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports.git'
    #vcpkgOverlayRef: 28b52673c26e29ccdce93ffa78413f26a0b11c8f
    #vcpkgPackages: ['cmakeshift', 'gsl-lite']
    vcpkgPackages: ['gsl-lite']

    cmakeSourceDir: '$(Build.SourcesDirectory)/ci/basic'
    cmakeConfigArgs: '-DBUILD_TESTING=ON -DCMAKESHIFT_WARNING_LEVEL=high'
    #cmakeTestArgs: '--exclude-regex cuda' # do not run CUDA tests

    postSetupSteps:
    - pwsh: |
        Write-Host 'Custom post-setup step (global)'
        Write-Host "C++ compiler: $env:CIMAKESHIFT_CXX_COMPILER, version: $env:CIMAKESHIFT_CXX_COMPILER_VERSION"
        Write-Host "CUDA compiler: $env:CIMAKESHIFT_CUDA_COMPILER, version: $env:CIMAKESHIFT_CUDA_COMPILER_VERSION"
      displayName: 'Custom post-setup step (global)'

    preBuildSteps:
    - pwsh: |
        Write-Host 'Custom pre-build step (global)'
        Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
      displayName: 'Custom pre-build step (global)'

    postBuildSteps:
    - pwsh: |
        Write-Host 'Custom post-build step (global)'
        Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
      displayName: 'Custom post-build step (global)'

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_1, 19_2, 12_3]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      #cxxCompilerVersions: [12, VS2022]
      cxxCompilerVersions: [13, VS2019]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [19_2]
      cudaCompiler: NVCC
      cudaCompilerVersions: [10_2, 11_4]
      platforms: [x64]
      vcpkgPackages: ['<vcpkgPackages>', 'catch2']
      cudaPackages: ['nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

      postSetupSteps:
      - pwsh: |
          Write-Host 'Custom post-setup step (target)'
          Write-Host "C++ compiler: $env:CIMAKESHIFT_CXX_COMPILER, version: $env:CIMAKESHIFT_CXX_COMPILER_VERSION"
          Write-Host "CUDA compiler: $env:CIMAKESHIFT_CUDA_COMPILER, version: $env:CIMAKESHIFT_CUDA_COMPILER_VERSION"
        displayName: 'Custom post-setup step (target)'

      preBuildSteps:
      - pwsh: |
          Write-Host 'Custom pre-build step (target)'
          Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
        displayName: 'Custom pre-build step (target)'

      postBuildSteps:
      - pwsh: |
          Write-Host 'Custom post-build step (target)'
          Write-Host "CMake build configuration: $env:CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION"
        displayName: 'Custom post-build step (target)'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [5, 10]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [11]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer]
      platforms: [x64]
      tag: 'sanitize'
      cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [4, 12]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [13]
      cxxStandardLibrary: libstdc++
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer, ImplicitIntegerArithmeticValueChange]
      platforms: [x64]
      tag: 'sanitize'
      vcpkgTriplet: <platform>-<os>-sanitize
      cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [6]
      cudaCompiler: NVCC
      cudaCompilerVersions: [10_2]
      platforms: [x64]
      cudaPackages: ['<cudaPackages>', 'nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [8]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_0]
      platforms: [x64]
      vcpkgPackages: ['catch2', 'cmakeshift', 'gsl-lite']
      cudaPackages: ['<cudaPackages>', 'nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [9]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_4]
      platforms: [x64]
      cudaPackages: ['<cudaPackages>', 'nvrtc-dev']
      cmakeConfigArgs: '<cmakeConfigArgs> -DBUILD_TESTING_CUDA=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [5, 11]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [9_1, 13]
      platforms: [x64]

- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    caption: Vcpkg manifests
    vcpkgRef: f79c681fc2b42f9c7c5024459b5a867d56ac6123

    cmakeSourceDir: '$(Build.SourcesDirectory)/ci/vcpkg-manifest'
    cmakeConfigArgs: '-DBUILD_TESTING=ON -DCMAKESHIFT_WARNING_LEVEL=high'

    targets:

    - os: Windows
      cxxCompiler: MSVC
      #cxxCompilerVersions: [19_3]
      cxxCompilerVersions: [19_2]
      platforms: [x64]

    - os: Windows
      cxxCompiler: Clang
      #cxxCompilerVersions: [12, VS2022]
      cxxCompilerVersions: [12, VS2019]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [11]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [13]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [11]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [13]
      platforms: [x64]
