# Internal template: run CMake tasks (config, build, test)

parameters:
  config: ''
  preBuildSteps: []
  postBuildSteps: []
  targetPreBuildSteps: []
  targetPostBuildSteps: []


steps:
- ${{ if coalesce(parameters.preBuildSteps, parameters.targetPreBuildSteps, parameters.postBuildSteps, parameters.targetPostBuildSteps) }}:
  - pwsh: |
      echo '##vso[task.setvariable variable=CIMAKESHIFT_CMAKE_BUILD_CONFIGURATION]${{ parameters.config }}'
    displayName: Set environment variables for build configuration

- ${{ each step in parameters.preBuildSteps }}:
  - ${{ each pair in step }}:
      ${{ pair.key }}: ${{ pair.value }}
- ${{ if parameters.targetPreBuildSteps }}:
  - ${{ each step in parameters.targetPreBuildSteps }}:
    - ${{ each pair in step }}:
        ${{ pair.key }}: ${{ pair.value }}

- ${{ if eq(parameters.cmakeConfig, 'true') }}:
  - pwsh: |
      New-Item -Type Directory -Force '$(Build.BinariesDirectory)/build/${{ parameters.config }}'
      cd '$(Build.BinariesDirectory)/build/${{ parameters.config }}'
      $vcpkgArgs = $env:CIMAKESHIFT_CMAKE_VCPKG_ARGS_ -split ' '
      $args = $env:CIMAKESHIFT_CMAKE_CONFIG_ARGS -split ' '
      & cmake -G $env:CIMAKESHIFT_CMAKE_GENERATOR -DCMAKE_BUILD_TYPE=${{ parameters.config }} $vcpkgArgs $env:CIMAKESHIFT_CMAKE_SOURCE_DIR $args
    displayName: 'Configure ${{ parameters.config }}'

- ${{ if eq(parameters.cmakeBuild, 'true') }}:
  - pwsh: |
      $args = $env:CIMAKESHIFT_CMAKE_BUILD_ARGS -split ' '
      & cmake --build '$(Build.BinariesDirectory)/build/${{ parameters.config }}' --parallel --verbose --config ${{ parameters.config }} $args
    displayName: 'Build ${{ parameters.config }}'

- ${{ if eq(parameters.cmakeTest, 'true') }}:
  - pwsh: |
      cd '$(Build.BinariesDirectory)/build/${{ parameters.config }}'
      $args = $env:CIMAKESHIFT_CMAKE_TEST_ARGS -split ' '
      & ctest --verbose --test-action Test --build-config ${{ parameters.config }} $args
    displayName: 'Run tests for ${{ parameters.config }}'

- ${{ each step in parameters.postBuildSteps }}:
  - ${{ each pair in step }}:
      ${{ pair.key }}: ${{ pair.value }}
- ${{ if parameters.targetPostBuildSteps }}:
  - ${{ each step in parameters.targetPostBuildSteps }}:
    - ${{ each pair in step }}:
        ${{ pair.key }}: ${{ pair.value }}
