x# Azure Pipelines job template for CMake builds
# Version 0.6.0
# Author: Moritz Beutel
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Supported compiler versions:
#
# Windows:
#   MSVC:               19_2, 19_3
#                       (also known as VS2019, VS2022)
#   Clang:              VS2019, VS2022
#                       (the version of Clang that ships with VS)
#   NVCC:               11_0, 11_1, 11_2, 11_3, 11_4, 11_5, 11_6, 11_7, 11_8, 12_0, 12_1, 12_2, 12_3
#
# Linux:
#   GCC:                7, 8, 9, 10, 11, 12, 13
#   Clang:              6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17
#   NVCC:               11_0, 11_1, 11_2, 11_3, 11_4, 11_5, 11_6, 11_7, 11_8, 12_0, 12_1, 12_2, 12_3
#
# MacOS:
#   GCC:                10, 11, 12, 13
#   AppleClang:         11_0_3, 12, 12_0_5, 13, 13_1_6, 14, 14_0_3, 15_0_1, 15_1, 15_2


# Supported C++ compilers per operating system:
#
#             | Windows     Linux       MacOS
# ============+====================================
# GCC         | -           X           X
# Clang       | X           X           -
# MSVC        | X           -           -
# AppleClang  | -           -           X


# Supported platforms per operating system:
#
#         | Windows     Linux       MacOS
# ========+====================================
# x86     | X           -           -
# x64     | X           X           X


# Supported standard libraries:
#
#               | GCC             Clang (Linux)   AppleClang      MSVC            Clang (Windows)
# ==============+================================================================================
# MS-STL        | -               -               -               X (default)     X (default)
# libstdc++     | X (default)     X               X               -               -
# libc++        | -               X (default)     X (default)     -               -


# Supported sanitizers:
#
#                                         | GCC     Clang/AppleClang    MSVC
# ========================================+======================================
# ASan/AddressSanitizer                   | X       X                   X
# UBSan/UndefinedBehaviorSanitizer        | X       X                   -
# ImplicitIntegerArithmeticValueChange    | -       X                   -


# Useful CUDA packages:
#
#   cublas-dev      cuBLAS headers and libraries
#   cufft-dev       cuFFT headers and libraries
#   curand-dev      cuRAND headers and libraries
#   cusolver-dev    cuSOLVER headers and libraries
#   cusparse-dev    cuSPARSE headers and libraries
#   nvgraph-dev     nvGRAPH headers and libraries
#   npp-dev         NPP headers and libraries
#   nvrtc-dev       NVRTC headers and libraries
#
# (cf. https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#install-cuda-software for Windows,
# https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ for Linux)


parameters:

  # Caption and tag for identification of the job
  # (note that captions and tags are restricted to the following characters: [A-Za-z0-9_.+ ])
  caption: ''
  tag: ''

  # Platform options
  os: ''
  platforms: []

  # C++ options
  cxxCompiler: ''
  cxxCompilerVersions: []
  cxxStandardLibrary: ''
  cxxStandardLibraryDebugMode: false
  cxxSanitizers: []

  # CUDA options (supported only on Linux and Windows)
  cudaCompiler: ''  # NVCC|Clang
  cudaCompilerVersions: [None]
  cudaPackages: []

  # Vcpkg repository
  vcpkgRepo: ''
  vcpkgRef: ''

  # Repository with additional port and triplet overlays
  vcpkgOverlayRepo: ''
  vcpkgOverlayRef: ''

  # Vcpkg options
  vcpkgTriplet: '<platform>-<os>'
  vcpkgArgs: ''
  vcpkgPackages: []
  vcpkgCache: '' # on by default if Vcpkg is used
  vcpkgCacheKey: ''

  # Build options
  cmakeSourceDir: '$(Build.SourcesDirectory)'
  cmakeToolchainFile: ''
  cmakeBuildConfigurations: [Debug, RelWithDebInfo]
  cmakeGenerator: ''
  cmakeConfig: true
  cmakeConfigArgs: ''
  cmakeBuild: true
  cmakeBuildArgs: ''
  cmakeTest: true
  cmakeTestArgs: ''

  # Build events
  postSetupSteps: []
  preBuildSteps: []
  postBuildSteps: []

  targets: []
#    target.caption                         # overrides parameters.caption
#    target.tag                             # overrides parameters.tag
#    target.os                              # overrides parameters.os
#    target.platforms                       # overrides parameters.platforms
#    target.cxxCompiler                     # overrides parameters.cxxCompiler
#    target.cxxCompilerVersions             # overrides parameters.cxxCompilerVersions
#    target.cxxStandardLibrary              # overrides parameters.cxxStandardLibrary
#    target.cxxStandardLibraryDebugMode     # overrides parameters.cxxStandardLibraryDebugMode
#    target.cxxSanitizers                   # overrides parameters.cxxSanitizers
#    target.cudaCompiler                    # overrides parameters.cudaCompiler
#    target.cudaCompilerVersions            # overrides parameters.cudaCompilerVersions
#    target.cmakeBuildConfigurations        # overrides parameters.cmakeBuildConfigurations
#    target.vcpkgRepo                       # overrides parameters.vcpkgRepo
#    target.vcpkgRef                        # overrides parameters.vcpkgRef
#    target.vcpkgOverlayRepo                # overrides parameters.vcpkgOverlayRepo
#    target.vcpkgOverlayRef                 # overrides parameters.vcpkgOverlayRef
#    target.vcpkgTriplet                    # overrides parameters.vcpkgTriplet
#    target.vcpkgArgs                       # overrides parameters.vcpkgArgs; can refer to parameters.vcpkgArgs as '<vcpkgArgs>'
#    target.vcpkgPackages                   # overrides parameters.vcpkgPackages; can refer to parameters.vcpkgPackages as '<vcpkgPackages>'
#    target.vcpkgCache                      # overrides parameters.vcpkgCache
#    target.vcpkgCacheKey                   # overrides parameters.vcpkgCacheKey; can refer to parameters.vcpkgCacheKey as '<vcpkgCacheKey>'
#    target.cudaPackages                    # overrides parameters.cudaPackages; can refer to parameters.cudaPackages as '<cudaPackages>'
#    target.cmakeToolchainFile              # overrides parameters.cmakeToolchainFile
#    target.cmakeGenerator                  # overrides parameters.cmakeGenerator
#    target.cmakeConfig                     # overrides parameters.cmakeConfig
#    target.cmakeConfigArgs                 # overrides parameters.cmakeConfigArgs; can refer to parameters.cmakeConfigArgs as '<cmakeConfigArgs>'
#    target.cmakeBuild                      # overrides parameters.cmakeBuild
#    target.cmakeBuildArgs                  # overrides parameters.cmakeBuildArgs; can refer to parameters.cmakeBuildArgs as '<cmakeBuildArgs>'
#    target.cmakeTest                       # overrides parameters.cmakeTest
#    target.cmakeTestArgs                   # overrides parameters.cmakeTestArgs; can refer to parameters.cmakeTestArgs as '<cmakeTestArgs>'
#    target.postSetupSteps                  # adds to parameters.postSetupSteps
#    target.preBuildSteps                   # adds to parameters.preBuildSteps
#    target.postBuildSteps                  # adds to parameters.postBuildSteps

jobs:
- ${{ each target in parameters.targets }}:
  - template: cmake_detail_job.yml
    parameters:
      cmakeSourceDir: '${{ parameters.cmakeSourceDir }}'
      postSetupSteps: ${{ parameters.postSetupSteps }}
      preBuildSteps: ${{ parameters.preBuildSteps }}
      postBuildSteps: ${{ parameters.postBuildSteps }}
      targetPostSetupSteps: ${{ target.postSetupSteps }}
      targetPreBuildSteps: ${{ target.preBuildSteps }}
      targetPostBuildSteps: ${{ target.postBuildSteps }}
      caption: '${{ coalesce(target.caption, parameters.caption) }}'
      tag: '${{ coalesce(target.tag, parameters.tag) }}'
      os: '${{ coalesce(target.os, parameters.os) }}'
      platforms:
      - ${{ if target.platforms }}:
        - ${{ target.platforms }}
      - ${{ if not(target.platforms) }}:
        - ${{ parameters.platforms }}
      cxxCompiler: '${{ coalesce(target.cxxCompiler, parameters.cxxCompiler) }}'
      cxxCompilerVersions:
      - ${{ if target.cxxCompilerVersions }}:
        - ${{ target.cxxCompilerVersions }}
      - ${{ if not(target.cxxCompilerVersions) }}:
        - ${{ parameters.cxxCompilerVersions }}
      cxxStandardLibrary: '${{ coalesce(target.cxxStandardLibrary, parameters.cxxStandardLibrary) }}'
      cxxStandardLibraryDebugMode: '${{ coalesce(target.cxxStandardLibraryDebugMode, parameters.cxxStandardLibraryDebugMode) }}'
      cxxSanitizers:
      - ${{ if target.cxxSanitizers }}:
        - ${{ target.cxxSanitizers }}
      - ${{ if not(target.cxxSanitizers) }}:
        - ${{ parameters.cxxSanitizers }}
      cudaCompiler: '${{ coalesce(target.cudaCompiler, parameters.cudaCompiler) }}'
      cudaCompilerVersions:
      - ${{ if target.cudaCompilerVersions }}:
        - ${{ target.cudaCompilerVersions }}
      - ${{ if not(target.cudaCompilerVersions) }}:
        - ${{ parameters.cudaCompilerVersions }}
      vcpkgRepo: '${{ coalesce(target.vcpkgRepo, parameters.vcpkgRepo) }}'
      vcpkgRef: '${{ coalesce(target.vcpkgRef, parameters.vcpkgRef) }}'
      vcpkgOverlayRepo: '${{ coalesce(target.vcpkgOverlayRepo, parameters.vcpkgOverlayRepo) }}'
      vcpkgOverlayRef: '${{ coalesce(target.vcpkgOverlayRef, parameters.vcpkgOverlayRef) }}'
      vcpkgTriplet: '${{ coalesce(target.vcpkgTriplet, parameters.vcpkgTriplet) }}'
      vcpkgCache: '${{ coalesce(target.vcpkgCache, parameters.vcpkgCache) }}'
      vcpkgCacheKey: '${{ coalesce(target.vcpkgCacheKey, parameters.vcpkgCacheKey) }}'
      cmakeToolchainFile: '${{ coalesce(target.cmakeToolchainFile, parameters.cmakeToolchainFile) }}'
      cmakeBuildConfigurations:
      - ${{ if target.cmakeBuildConfigurations }}:
        - ${{ target.cmakeBuildConfigurations }}
      - ${{ if not(target.cmakeBuildConfigurations) }}:
        - ${{ parameters.cmakeBuildConfigurations }}
      cmakeGenerator: '${{ coalesce(target.cmakeGenerator, parameters.cmakeGenerator) }}'
      cmakeConfig: '${{ coalesce(target.cmakeConfig, parameters.cmakeConfig) }}'
      cmakeBuild: '${{ coalesce(target.cmakeBuild, parameters.cmakeBuild) }}'
      cmakeTest: '${{ coalesce(target.cmakeTest, parameters.cmakeTest) }}'
      cudaPackages: '${{ replace(coalesce(join('' '', target.cudaPackages), ''<cudaPackages>''), ''<cudaPackages>'', join('' '', parameters.cudaPackages)) }}'
      vcpkgPackages: '${{ replace(coalesce(join('' '', target.vcpkgPackages), ''<vcpkgPackages>''), ''<vcpkgPackages>'', join('' '', parameters.vcpkgPackages)) }}'
      vcpkgArgs: '${{ replace(coalesce(target.vcpkgArgs, ''<vcpkgArgs>''), ''<vcpkgArgs>'', parameters.vcpkgArgs) }}'
      cmakeConfigArgs: '${{ replace(coalesce(target.cmakeConfigArgs, ''<cmakeConfigArgs>''), ''<cmakeConfigArgs>'', parameters.cmakeConfigArgs) }}'
      cmakeBuildArgs: '${{ replace(coalesce(target.cmakeBuildArgs, ''<cmakeBuildArgs>''), ''<cmakeBuildArgs>'', parameters.cmakeBuildArgs) }}'
      cmakeTestArgs: '${{ replace(coalesce(target.cmakeTestArgs, ''<cmakeTestArgs>''), ''<cmakeTestArgs>'', parameters.cmakeTestArgs) }}'
